import { Project, Category } from '@/types';

// Mock categories data
export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Web Apps',
    slug: 'web-apps',
    description: 'Modern web applications and SaaS tools',
    icon: 'Globe',
    color: 'blue',
    projectCount: 156,
    order: 1,
  },
  {
    id: '2',
    name: 'Mobile Apps',
    slug: 'mobile-apps',
    description: 'iOS and Android applications',
    icon: 'Smartphone',
    color: 'green',
    projectCount: 89,
    order: 2,
  },
  {
    id: '3',
    name: 'AI & ML',
    slug: 'ai-ml',
    description: 'Artificial intelligence and machine learning tools',
    icon: 'Brain',
    color: 'purple',
    projectCount: 67,
    order: 3,
  },
  {
    id: '4',
    name: 'Developer Tools',
    slug: 'developer-tools',
    description: 'Tools and utilities for developers',
    icon: 'Code',
    color: 'orange',
    projectCount: 134,
    order: 4,
  },
  {
    id: '5',
    name: 'E-commerce',
    slug: 'ecommerce',
    description: 'Online stores and marketplace solutions',
    icon: 'ShoppingCart',
    color: 'red',
    projectCount: 78,
    order: 5,
  },
  {
    id: '6',
    name: 'Productivity',
    slug: 'productivity',
    description: 'Tools to boost productivity and efficiency',
    icon: 'Zap',
    color: 'yellow',
    projectCount: 92,
    order: 6,
  },
  {
    id: '7',
    name: 'Design Tools',
    slug: 'design-tools',
    description: 'Creative tools for designers and artists',
    icon: 'Palette',
    color: 'pink',
    projectCount: 45,
    order: 7,
  },
  {
    id: '8',
    name: 'Finance',
    slug: 'finance',
    description: 'Financial tools and fintech solutions',
    icon: 'DollarSign',
    color: 'emerald',
    projectCount: 56,
    order: 8,
  },
];

// Mock featured projects data
export const mockFeaturedProjects: Project[] = [
  {
    id: '1',
    name: 'TaskFlow Pro',
    tagline: 'The ultimate project management tool for modern teams',
    description: 'TaskFlow Pro revolutionizes how teams collaborate and manage projects. With intuitive kanban boards, real-time collaboration, and powerful analytics, it\'s the only tool your team needs to stay productive and organized.',
    websiteUrl: 'https://taskflowpro.com',
    logoUrl: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=64&h=64&fit=crop&crop=center',
    screenshotUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
    category: 'Productivity',
    tags: ['project-management', 'collaboration', 'productivity', 'teams'],
    teamSize: '3-5',
    foundedYear: 2023,
    submitterId: 'user1',
    submitterEmail: 'founder@taskflowpro.com',
    submitterName: 'Sarah Johnson',
    status: 'approved',
    voteCount: 247,
    viewCount: 3420,
    clickCount: 892,
    submittedAt: new Date('2024-01-15') as any,
    approvedAt: new Date('2024-01-16') as any,
    socialLinks: {
      twitter: 'https://twitter.com/taskflowpro',
      github: 'https://github.com/taskflowpro',
      producthunt: 'https://producthunt.com/posts/taskflowpro',
    },
  },
  {
    id: '2',
    name: 'CodeSnap AI',
    tagline: 'AI-powered code screenshot generator with syntax highlighting',
    description: 'Create beautiful code screenshots instantly with AI-powered syntax highlighting, custom themes, and automatic formatting. Perfect for documentation, social media, and presentations.',
    websiteUrl: 'https://codesnap.ai',
    logoUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=64&h=64&fit=crop&crop=center',
    screenshotUrl: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&h=600&fit=crop',
    category: 'Developer Tools',
    tags: ['ai', 'code', 'screenshots', 'developer-tools'],
    teamSize: '1',
    foundedYear: 2024,
    submitterId: 'user2',
    submitterEmail: 'hello@codesnap.ai',
    submitterName: 'Alex Chen',
    status: 'approved',
    voteCount: 189,
    viewCount: 2156,
    clickCount: 567,
    submittedAt: new Date('2024-01-20') as any,
    approvedAt: new Date('2024-01-21') as any,
    socialLinks: {
      twitter: 'https://twitter.com/codesnapai',
      github: 'https://github.com/codesnapai',
    },
  },
  {
    id: '3',
    name: 'ShopifyPlus Analytics',
    tagline: 'Advanced analytics dashboard for Shopify store owners',
    description: 'Get deep insights into your Shopify store performance with advanced analytics, customer behavior tracking, and revenue optimization suggestions. Increase your sales with data-driven decisions.',
    websiteUrl: 'https://shopifyplus-analytics.com',
    logoUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=64&h=64&fit=crop&crop=center',
    screenshotUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
    category: 'E-commerce',
    tags: ['shopify', 'analytics', 'ecommerce', 'dashboard'],
    teamSize: '5-10',
    foundedYear: 2022,
    submitterId: 'user3',
    submitterEmail: 'team@shopifyplus-analytics.com',
    submitterName: 'Mike Rodriguez',
    status: 'approved',
    voteCount: 156,
    viewCount: 1890,
    clickCount: 423,
    submittedAt: new Date('2024-01-25') as any,
    approvedAt: new Date('2024-01-26') as any,
    socialLinks: {
      twitter: 'https://twitter.com/shopifyplusanalytics',
    },
  },
  {
    id: '4',
    name: 'MindMap Studio',
    tagline: 'Collaborative mind mapping tool for creative teams',
    description: 'Create stunning mind maps collaboratively with your team. Features real-time editing, infinite canvas, and beautiful templates. Perfect for brainstorming, planning, and visual thinking.',
    websiteUrl: 'https://mindmapstudio.app',
    logoUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=64&h=64&fit=crop&crop=center',
    screenshotUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop',
    category: 'Design Tools',
    tags: ['mind-mapping', 'collaboration', 'design', 'brainstorming'],
    submitterId: 'user4',
    submitterEmail: 'hello@mindmapstudio.app',
    submitterName: 'Emma Wilson',
    status: 'approved',
    voteCount: 203,
    viewCount: 2734,
    clickCount: 678,
    submittedAt: new Date('2024-02-01') as any,
    approvedAt: new Date('2024-02-02') as any,
    socialLinks: {
      twitter: 'https://twitter.com/mindmapstudio',
      github: 'https://github.com/mindmapstudio',
    },
  },
  {
    id: '5',
    name: 'CryptoTracker Pro',
    tagline: 'Professional cryptocurrency portfolio tracker and analyzer',
    description: 'Track your crypto investments with professional-grade tools. Real-time prices, portfolio analytics, tax reporting, and advanced charting. Trusted by thousands of crypto investors.',
    websiteUrl: 'https://cryptotracker.pro',
    logoUrl: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=64&h=64&fit=crop&crop=center',
    screenshotUrl: 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800&h=600&fit=crop',
    category: 'Finance',
    tags: ['cryptocurrency', 'portfolio', 'finance', 'tracking'],
    submitterId: 'user5',
    submitterEmail: 'support@cryptotracker.pro',
    submitterName: 'David Kim',
    status: 'approved',
    voteCount: 312,
    viewCount: 4567,
    clickCount: 1234,
    submittedAt: new Date('2024-02-05') as any,
    approvedAt: new Date('2024-02-06') as any,
    socialLinks: {
      twitter: 'https://twitter.com/cryptotrackerpro',
    },
  },
  {
    id: '6',
    name: 'FitnessPal AI',
    tagline: 'AI-powered personal fitness and nutrition coach',
    description: 'Get personalized workout plans and nutrition advice powered by AI. Track your progress, set goals, and achieve your fitness dreams with intelligent coaching that adapts to your lifestyle.',
    websiteUrl: 'https://fitnesspal.ai',
    logoUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=64&h=64&fit=crop&crop=center',
    screenshotUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
    category: 'Mobile Apps',
    tags: ['fitness', 'ai', 'health', 'mobile-app'],
    submitterId: 'user6',
    submitterEmail: 'team@fitnesspal.ai',
    submitterName: 'Lisa Thompson',
    status: 'approved',
    voteCount: 178,
    viewCount: 2345,
    clickCount: 567,
    submittedAt: new Date('2024-02-10') as any,
    approvedAt: new Date('2024-02-11') as any,
    socialLinks: {
      twitter: 'https://twitter.com/fitnesspalai',
      producthunt: 'https://producthunt.com/posts/fitnesspal-ai',
    },
  },
];
